### ISSUE TITLE
Make single fuels-rs crates that exports everything needed for tests

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-rs#164]
Rather than needing to set

```toml
fuel-gql-client = {{ version = "0.4", default-features = false }}
fuel-tx = "0.6"
fuels-abigen-macro = "0.6"
fuels-contract = "0.6"
fuels-core = "0.6"
rand = "0.8"
tokio = {{ version = "1.12", features = ["rt", "macros"] }}
```

in `Cargo.toml` for Sway tests, there should be a single `fuels-rs` crate that exports all needed dependencies, such that users only need a single one.
