### ISSUE TITLE
Configuration-time constants

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#588]
Sway currently supports constants declared in `Forc.toml`, e.g.: 

```toml
[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "oracle"

[constants]
# Change to an Identity once https://github.com/FuelLabs/sway/issues/2647 is fixed
owner = { type = "b256", value = "0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db" }

[dependencies]
```

The SDK must offer support for this feature so that users can, in their Rust code, set the value of a constant and deploy the contract without the need to recompile the code.

To achieve this, the compiler will output a new piece of data (e.g., a new file similar to the JSON ABI) that will tell us the type of the constant, name (? tbd), and its _location in the compiled bytecode_. With this information, the SDK should inject that constant's value into the compiled bytecode before deploying it. 

Note that there will be more discussions on the specifics of how this is going to be achieved. The Sway compiler currently blocks this work until then.
