### ISSUE TITLE
Is it possible to convert `String` representation of of `Bech32ContractId` into a `ContractId`?

### ISSUE THREAD

**Issue by ra0x3** [FuelLabs/fuels-rs#774]
### Background
- On the indexer, users want to be able to filter `Receipt` events based on which contract is sending the `Receipt`
  - Here is a user requesting that functionality https://github.com/FuelLabs/fuel-indexer/issues/451
- The `id`property of many `Receipt` types, is of type `ContractId` ([here is the where `ContractId` is defined in `fuel-types`](https://github.com/FuelLabs/fuel-types/blob/master/src/types.rs#L267))
- However, after a user deploys a contract using `Contract::deploy` the contract ID that is returned to the user is of type `Bech32ContractId`
- Users can then take the `String` representation of that `Bech32ContractId` (e.g., `fuel1hpqhnm0685tsqkvqwej8v8vl6gp5j39hcnee7uxkmqnc0pxjj7kq07scwj`) and add that to their index manifest, so that they can filter for only `Receipt` events from a particular contract
- So a user's index manifest would look similar to:

```yaml
namespace: fuel_examples
identifier: hello_index
contract_id: fuel1hpqhnm0685tsqkvqwej8v8vl6gp5j39hcnee7uxkmqnc0pxjj7kq07scwj
abi: greeting-abi.json
start_block: 1
graphql_schema: hello_index.schema.graphql
module:
  wasm: hello_index.wasm
```

### The issue
- However, the issue is that we on the indexer are not sure how to take the `String` representation of a `Bech32ContractId` (e.g., `fuel1hpqhnm0685tsqkvqwej8v8vl6gp5j39hcnee7uxkmqnc0pxjj7kq07scwj`) and convert that back into a `ContractId` type
- Why do we need to do this?
  - Because we would like to compare the `contract_id` specified in an index manifest, with the `id` property of the `Receipt` objects, to ensure we're only sending users events from their specified contract

This has some priority for us on the indexer, since this is an issue an actual user/team is running into currently
